version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:alpine

  ui:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./ui:/usr/share/nginx/html:ro
