apiVersion: v1
kind: Pod
metadata:
  name: mlops-pod
  labels:
    app: mlops-app

spec:
  containers:
    - name: mlops-container
      image: manifoldailearning/mid-program-project-demo:latest
      ports:
        - containerPort: 7860