apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-container
          image: busybox
          command: ["/bin/sh", "-c", "while true; do cat /app/config/.env ; sleep 5; done"]
          volumeMounts:
            - name: env-config-volume
              mountPath: /app/config
      volumes:
        - name: env-config-volume
          configMap:
            name: env-config