apiVersion: v1
kind: Secret
metadata:
  name: demosecret
type: Opaque
data:
  username: YWRtaW4=
  password: cGFzc3dvcmQ=

---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
    - name: demo-container
      image: busybox
      command: ["/bin/sh", "-c", "echo $username $password"]
      env:
        - name: username
          valueFrom:
            secretKeyRef:
              name: demosecret
              key: username
        - name: password
          valueFrom:
            secretKeyRef:
              name: demosecret
              key: password