apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-deployment
  namespace: mlops-namespace # Specify the namespace for the deployment

# This is a deployment that manages the pods

spec:
  replicas: 3
  selector:
    matchLabels:
      app: mlops-app-deployment #Which pods to manage
  template: # Individual pod information
    metadata:
      labels:
        app: mlops-app-deployment # Labels for the pod
    spec: # Container information
      # This is the container that will be created in the pod
      containers:
        - name: mlops-container
          image: manifoldailearning/mid-program-project-demo:latest
          ports:
            - containerPort: 7860

---
apiVersion: v1
kind: Service
metadata:
  name: mlops-service
  namespace: mlops-namespace # Specify the namespace for the service
spec:
  type: NodePort
  selector:
    app: mlops-app
  ports:
    - protocol: TCP
      port: 7861 # port of the services
      targetPort: 7860 # Port of the container
      nodePort: 30080 # Port of the node